# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ef32179fc9a48182ef375dbeb5b95800286f58791a84aeb3b83fdfa51580da1e2fffe1fe78925ce560fdf6d21bc05f05f4e9da211534729189145433444b3b7

test:
  secret_key_base: 1116c931fc9dada5bed0572e4ba11178e2c5b2b922cb2a4a415dfef34dfa90c17723ff7863dfb157a3a7e1b7e081745d8bae48978ccdba498da28b2c5d99f1e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
